apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: aquapredict
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nextjs
        image: <region>.ocir.io/<tenancy>/aquapredict/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://prediction-service"
        - name: NEXT_PUBLIC_MAPBOX_TOKEN
          valueFrom:
            secretKeyRef:
              name: mapbox-credentials
              key: token
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
      imagePullSecrets:
      - name: ocir-secret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: aquapredict
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
